# -*- coding: utf-8 -*-
"""BreakHis_Patches.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnzwzEnjR6ot6_lFtBjh9SmskL0JEkYf
"""


from glob import glob
import matplotlib.pyplot as plt

import os
import numpy as np
from utils import misc_utils as mu


#This code will work on individul class you have to add path or each class and it will extact the patches from images  for both(binary and multi class)
### change me ###
root_dir = '/content/drive/My Drive/BreaKHis_v1/'

###
data_dir = root_dir + '8cls/Rename_BreakHis/Rename_8cls/400'
save_dir_train = root_dir + 'New_patches/8cls_patches/400'



#Please Give individaul Class name with there prefixes name
#change again and again according to the class name
classes = ('B_A',)
prefixes = {'B_A': 'b_a',}

def get_patches(img, save_path_sub):
    cnt = 1
    for i in range(2):
        for j in range(3):
            patch = img[112 * i:112 * i + 224, 112 * j:112 * j + 224]
            mu.save_aspng(patch, save_path_sub + '_patch' + mu.i2str(cnt) + '.png', compression=1)
            cnt += 1

for c in classes:
    for i in range(1,6000):
        filename = prefixes[c] + mu.i2str(i + 1) +'.png'
        print('Doing Image {}'.format(filename))
        path = os.path.join(data_dir, c, filename)
        image = mu.read_image(path)
        sub = os.path.join(save_dir_train, c, prefixes[c] + mu.i2str(i + 1))
        get_patches(image, sub)

# classes = ( 'B_F', 'B_PT', 'B_TA','M_DC','M_LC','M_MC','M_PC')
# prefixes = { 'B_F': 'bf', 'B_PT': 'bpt', 'B_TA': 'bta','M_DC': 'mdc', 'M_LC': 'mlc', 'M_MC': 'mmc', 'M_PC': 'mpc'}