# -*- coding: utf-8 -*-
"""Rename BreakHis .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16i74UotEQdjAL3ctTNJWgnYvZxXWFAbd
"""

from google.colab import drive
drive.mount('/content/drive')

#roo = '/content/drive/My Drive/BreaKHis_v1/8cls/8_Cls_One_data/40'

import os
from shutil import copyfile
base_path = '/content/drive/My Drive/BreaKHis_v1/tf_files/200X'
traget_dir = '/content/drive/My Drive/BreaKHis_v1/8cls/Rename_BreakHis/Rename_2cls/200'

folders = os.listdir(base_path)

for folder in folders:
  os.mkdir(os.path.join(traget_dir, folder))
  files = [x for x in sorted(os.listdir(os.path.join(base_path, folder))) if x[-4:].lower() == '.png']
  #print(files)
  for i, name in enumerate(files):
    if i<9:
      n_name = '00'+str(i+1)
    elif i<99:
      n_name = '0'+str(i+1)
    elif i<999:
      n_name = str(i+1)  
    else:
      n_name = str(i+1)

    copyfile(os.path.join(base_path, folder, name), os.path.join(traget_dir, folder,folder.lower()+n_name+'.png'))

len(files)